### PR TITLE
bug fixes, code cleanup, language cleanup

### PR DESCRIPTION
**Pull request by heythisisnate**
There's a bug here when the device's IP or port changes. It's not totally solved here, I'm still debugging. It's getting late and I wanted to capture my progress here.

@copy-ninja maybe you can explain the difference between `state.devices` and `state.alarmPanel` here and why we need both? Also what is supposed to update `state.devices` ... that doesn't seem to be happening.

### CODE REVIEW

**Comment by copy-ninja** [comment]
@heythisisnate `state.devices` is only used for discovery while `state.alarmPanel` is for selected devices through smartapp. I didn't bother to update the IP address for `state.devices` because of that. and frankly, `state.devices` portion of codes were copied from http://docs.smartthings.com/en/latest/cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.html#verification I haven't cleaned it up yet.

**Comment by heythisisnate** [comment]
I see. The problem is that every time `getSelectedAlarmPanel()` is called, it rebuilds `state.alarmPanel` from the device information stored in `state.devices`. So, even when you save updates to the IP address or port in `state.alarmPanel` it is almost immediately overwritten.

Is there any reason to have two persistent state constructs that contain basically the same information? When I was digging into this last night it felt like it could be simplified to just use one or the other, rather than having to update both when network details change.

**Comment by copy-ninja** [comment]
Yea, this area definitely can be improved.

**Comment by heythisisnate** [comment]
Ok @copy-ninja this is ready to go I think. A few things fixed/improved in this PR:
1. fixes issue where IP or port changes wouldn't persist
1. simplifies the app state, relying only on `state.devices` for information about discovered and configured devices. `state.alarmPanel` is no longer needed
1. fix method call with undefined signature
1. rename some functions for better clarity
1. helper function to generate IP:PORT string from a device hash map

**Comment by heythisisnate** [comment]
@copy-ninja I'm going to go ahead and merge this so I can get mine and my neighbor's siren working again (some time pressure to get it fixed). Seems like you're busy this weekend. We can always make changes later.

**Pull request merged**
