### PR TITLE
blink led on success

### PR DESCRIPTION
**Pull request by heythisisnate**
This blinks the LED on successful communication with ST. Similar in functionality to my initial release.

### CODE REVIEW

**Comment by heythisisnate** [comment]
@copy-ninja this should work now, after rebasing your `variables.lua` optimizations and some other tweaks, we have enough memory now.

**Comment by heythisisnate** [comment]
Probably not totally necessary, but I'm just trying to get to feature parity. Why do you not like the option?

**Comment by copy-ninja** [comment]
pin 4 is discouraged from being used anyway since you'll get problem during bootup if it's hooked up and it's used to indicate connectivity. we should keep things simple on the options. that way we can maintain a consistent behavior of the indicator.

besides, it'll be a globally declared variable. the less memory used, the better. and we don't have to program more stuff on smartapp to let people configure this.

**Comment by heythisisnate** [comment]
Ok I removed the option

**Comment by copy-ninja** [comment]
Good to go!

**Pull request merged**
